# TravisCI configuration for decodelabs/atlas

language: 'php'
os:
    - 'linux'
dist: 'bionic'

php:
    - '8.0'
    - '7.4'
    - '7.3'
    - '7.2'

cache:
    directories:
        - '${HOME}/.composer/cache'

before_install:
    - 'sudo apt-get update'
    - 'sudo apt-get install libevent-dev'
    - 'composer validate --strict'

install:
    - 'composer update --no-interaction --prefer-dist'

before_script:
    - "yes '' | pecl install event"

script:
    - 'composer run-script analyze -- --no-interaction'
    - 'composer run-script psr12'
